pipeline {
    agent {
        node {
            label 'perm-ubuntu-agent'
        }
    }
    environment {
        TAG = VersionNumber(versionNumberString: '${BUILD_DATE_FORMATTED, "yyyyMMdd"}', versionPrefix: 'v', worstResultForIncrement: 'SUCCESS')
    }
    triggers {
        pollSCM '*/5 * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Build stage"
                sh 'git clone https://github.com/Krylovv/DevPet/'
                sh 'docker build -t kryloff/devpet:${TAG} ./Code/WebApp'
                sh 'rm -rf ~/workspace/devpet_pipeline/*'
            }
        }
        stage('Test') {
            steps {
                echo "Test stage"
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploy stage"
                sh 'docker push kryloff/devpet:${TAG}'
                sh 'docker image rm kryloff/devpet:${TAG}'
                sh 'minikube kubectl -- set image deployment/devpet-app devpet-app=kryloff/devpet:${TAG}'
                sh 'minikube kubectl -- get rs'
            }
        }
    }
}

